### PR TITLE
Updated project to be compatible with Material-UI Pickers v4

### PR DESCRIPTION
**Pull request by emulienfou**
* Dependencies upgraded
* Added `DateRangeInput`
* Docs updated

> Related to issue #51

### CODE REVIEW

**Comment by tretapey** [comment]
I really need this

**Comment by srosset81** [comment]
Any chance of having this merged ?

**Comment by andrekutianski** [comment]
project abandoned guys

**Comment by MirzaKabiljagic** [comment]
> project abandoned guys

Can this be used still or no point?

**Pull request closed without merging**
